/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PhongKham.ui;

import PhongKham.dao.HoaDonChiTietDao;
import PhongKham.ui.*;
import PhongKham.dao.HoaDonThuocDao;
import PhongKham.entity.HoaDonChiTietPK;
import PhongKham.entity.HoaDonThuocPK;
import PhongKham.dao.ThuocDao;
import PhongKham.entity.ThuocPK;
import PhongKham.utils.MsgBox;
import PhongKham.utils.XDate;
import PhongKham.utils.XImage;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class HoaDonThuocGD extends javax.swing.JPanel {

      DefaultComboBoxModel model;

    public HoaDonThuocGD() {
        initComponents();
        this.init();
       
    }

    
    
//bị gì nữa
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        NhanVien = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ThongTinBS = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaHDT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        txtMaBN = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboChuanDoan = new combo_suggestion.ComboBoxSuggestion();
        JDCNgayXuat = new com.toedter.calendar.JDateChooser();
        btnMoi1 = new javax.swing.JButton();
        btnKeToa = new javax.swing.JButton();
        tblbangbacsy = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachHDTT = new javax.swing.JTable();
        Container = new javax.swing.JPanel();
        HoaDonChiTiet = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHDCT = new javax.swing.JTable();
        lblTongHD = new javax.swing.JLabel();
        txtTongHoaDn = new javax.swing.JTextField();
        KeToa = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMaBN1 = new javax.swing.JTextField();
        txtMaBN3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKeThuoc = new javax.swing.JTable();

        setBackground(new java.awt.Color(93, 167, 219));
        setPreferredSize(new java.awt.Dimension(1600, 900));

        NhanVien.setBackground(new java.awt.Color(93, 167, 219));
        NhanVien.setPreferredSize(new java.awt.Dimension(1600, 900));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mã HDCT : ");

        ThongTinBS.setBackground(new java.awt.Color(129, 198, 232));
        ThongTinBS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Toa Thuốc    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        ThongTinBS.setToolTipText("");
        ThongTinBS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Mã Hóa Đơn Thuốc : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Chuẩn Đoán  : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Ngày Xuất  : ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Mã BN  :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Mã NV  : ");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/tablet.png"))); // NOI18N

        btnMoi1.setBackground(new java.awt.Color(0, 0, 255));
        btnMoi1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMoi1.setForeground(new java.awt.Color(255, 51, 51));
        btnMoi1.setText("Hóa Đơn Chi Tiết");
        btnMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoi1ActionPerformed(evt);
            }
        });

        btnKeToa.setBackground(new java.awt.Color(0, 0, 255));
        btnKeToa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnKeToa.setForeground(new java.awt.Color(255, 51, 51));
        btnKeToa.setText("Kê Toa");
        btnKeToa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeToaMouseClicked(evt);
            }
        });
        btnKeToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeToaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ThongTinBSLayout = new javax.swing.GroupLayout(ThongTinBS);
        ThongTinBS.setLayout(ThongTinBSLayout);
        ThongTinBSLayout.setHorizontalGroup(
            ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinBSLayout.createSequentialGroup()
                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaHDT, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTinBSLayout.createSequentialGroup()
                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongTinBSLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(53, 53, 53)
                                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboChuanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JDCNgayXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ThongTinBSLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ThongTinBSLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ThongTinBSLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(109, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTinBSLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMoi1)
                            .addComponent(btnKeToa, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))))
        );
        ThongTinBSLayout.setVerticalGroup(
            ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinBSLayout.createSequentialGroup()
                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongTinBSLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMaHDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10)
                                    .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboChuanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTinBSLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(ThongTinBSLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)))
                        .addGap(31, 31, 31)
                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JDCNgayXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnKeToa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(btnMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnThem.getAccessibleContext().setAccessibleName("");
        btnXoa.getAccessibleContext().setAccessibleName("");
        btnSua.getAccessibleContext().setAccessibleName("");
        btnMoi.getAccessibleContext().setAccessibleName("");

        tblbangbacsy.setBackground(new java.awt.Color(129, 198, 232));
        tblbangbacsy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Hóa Đơn Thuốc  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        tblDanhSachHDTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MaNV", "HoTenNV", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14"
            }
        ));
        tblDanhSachHDTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachHDTTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachHDTT);

        javax.swing.GroupLayout tblbangbacsyLayout = new javax.swing.GroupLayout(tblbangbacsy);
        tblbangbacsy.setLayout(tblbangbacsyLayout);
        tblbangbacsyLayout.setHorizontalGroup(
            tblbangbacsyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblbangbacsyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        tblbangbacsyLayout.setVerticalGroup(
            tblbangbacsyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblbangbacsyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        Container.setLayout(new java.awt.CardLayout());

        HoaDonChiTiet.setBackground(new java.awt.Color(255, 255, 204));
        HoaDonChiTiet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn Thuốc Chi Tiết   ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        tblHDCT.setBackground(new java.awt.Color(255, 255, 204));
        tblHDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblHDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHDCTMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHDCT);

        lblTongHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongHD.setForeground(new java.awt.Color(255, 0, 0));
        lblTongHD.setText("Tổng Hóa Đơn Thuốc :  ");

        txtTongHoaDn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtTongHoaDn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTongHoaDn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongHoaDnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HoaDonChiTietLayout = new javax.swing.GroupLayout(HoaDonChiTiet);
        HoaDonChiTiet.setLayout(HoaDonChiTietLayout);
        HoaDonChiTietLayout.setHorizontalGroup(
            HoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HoaDonChiTietLayout.createSequentialGroup()
                        .addComponent(lblTongHD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTongHoaDn, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );
        HoaDonChiTietLayout.setVerticalGroup(
            HoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonChiTietLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(HoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HoaDonChiTietLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(HoaDonChiTietLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txtTongHoaDn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(83, Short.MAX_VALUE))))
        );

        Container.add(HoaDonChiTiet, "card2");

        KeToa.setBackground(new java.awt.Color(255, 255, 204));
        KeToa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kê Toa Thuốc   ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Tên Thuốc   : ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Số Lượng   : ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Liều Dùng   :");

        tblKeThuoc.setBackground(new java.awt.Color(255, 255, 204));
        tblKeThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(tblKeThuoc);
        if (tblKeThuoc.getColumnModel().getColumnCount() > 0) {
            tblKeThuoc.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            tblKeThuoc.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            tblKeThuoc.getColumnModel().getColumn(3).setHeaderValue("Title 4");
            tblKeThuoc.getColumnModel().getColumn(4).setHeaderValue("Title 5");
        }

        javax.swing.GroupLayout KeToaLayout = new javax.swing.GroupLayout(KeToa);
        KeToa.setLayout(KeToaLayout);
        KeToaLayout.setHorizontalGroup(
            KeToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeToaLayout.createSequentialGroup()
                .addGroup(KeToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeToaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel11)
                        .addGap(51, 51, 51)
                        .addComponent(txtMaBN3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KeToaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel12)
                        .addGap(56, 56, 56)
                        .addComponent(txtMaBN1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KeToaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel14)
                        .addGap(56, 56, 56)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeToaLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        KeToaLayout.setVerticalGroup(
            KeToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeToaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(KeToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeToaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel11))
                    .addComponent(txtMaBN3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(KeToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtMaBN1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(KeToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeToaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Container.add(KeToa, "card3");

        javax.swing.GroupLayout NhanVienLayout = new javax.swing.GroupLayout(NhanVien);
        NhanVien.setLayout(NhanVienLayout);
        NhanVienLayout.setHorizontalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienLayout.createSequentialGroup()
                .addGroup(NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NhanVienLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ThongTinBS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tblbangbacsy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NhanVienLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        NhanVienLayout.setVerticalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NhanVienLayout.createSequentialGroup()
                        .addGroup(NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ThongTinBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tblbangbacsy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 1616, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:   
        if(getForm() == null){
            this.insert();
        }else{
            MsgBox.alert(this, "Xin Mời nhập Thuốc");
            KeToa.setVisible(true);
             HoaDonChiTiet.setVisible(false);
        }
        
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void tblDanhSachHDTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachHDTTMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.row = tblDanhSachHDTT.getSelectedRow();
            this.edit();
            
        }
      this.fillTableHDCT();
      this.getsum();
      HoaDonChiTiet.setVisible(true);
      KeToa.setVisible(false);
    }//GEN-LAST:event_tblDanhSachHDTTMouseClicked

    private void txtTongHoaDnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongHoaDnActionPerformed
        // TODO add your handling code here:
//        this.getsum();
    }//GEN-LAST:event_txtTongHoaDnActionPerformed

    private void btnMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoi1ActionPerformed
        // TODO add your handling code here:
         HoaDonChiTiet.setVisible(true);
         KeToa.setVisible(false);
    }//GEN-LAST:event_btnMoi1ActionPerformed

    private void btnKeToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeToaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeToaActionPerformed

    private void btnKeToaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeToaMouseClicked
        // TODO add your handling code here:
         KeToa.setVisible(true);
        HoaDonChiTiet.setVisible(false);
    }//GEN-LAST:event_btnKeToaMouseClicked

    private void tblHDCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHDCTMouseClicked
        // TODO add your handling code here:
//       if(evt.getClickCount() == 1){
//            this.row = tblDanhSachHDTT.getSelectedRow();
//            this.edit();
//        }
//        if(evt.getClickCount() == 1){
//        String mabn = (String) tblDanhSachHDTT.getValueAt(this.row, 1);
//        HoaDonThuocPK  tt = dao.selectById(mabn);
//        this.setForm(tt);
//            ThuocChiTiet tory = new ThuocChiTiet(tt);
//        tory.setVisible(true);
//        }
//        
    }//GEN-LAST:event_tblHDCTMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel HoaDonChiTiet;
    private com.toedter.calendar.JDateChooser JDCNgayXuat;
    private javax.swing.JPanel KeToa;
    private javax.swing.JPanel NhanVien;
    private javax.swing.JPanel ThongTinBS;
    private javax.swing.JButton btnKeToa;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnMoi1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private combo_suggestion.ComboBoxSuggestion cboChuanDoan;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTongHD;
    private javax.swing.JTable tblDanhSachHDTT;
    private javax.swing.JTable tblHDCT;
    private javax.swing.JTable tblKeThuoc;
    private javax.swing.JPanel tblbangbacsy;
    private javax.swing.JTextField txtMaBN;
    private javax.swing.JTextField txtMaBN1;
    private javax.swing.JTextField txtMaBN3;
    private javax.swing.JTextField txtMaHDT;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongHoaDn;
    // End of variables declaration//GEN-END:variables
    
    HoaDonThuocDao dao = new HoaDonThuocDao();
    HoaDonChiTietDao daodao = new HoaDonChiTietDao();
    
    int row = -1;

    void init() {
        initTable();
        this.fillTable();
        initTablee();
        this.row = -1;
        this.initcombobox();
        initTableee();
//        TongHoaDon();
        
    }
    public void initcombobox(){ 
        this.setBackground(new Color(255, 255, 255));
        String[] chuandoan = {"Suy giảm miễn dịch","Bệnh cúm","Trật khớp vai","Rối loạn miễn dịch","Suy dinh dưỡng thai nhi","Sốt xuất huyết","Nhiệt miệng",
            "Stress","Viêm phụ khoa","Tiêu chảy cấp","Đau mắt đỏ","Quai bị","Gãy xương chân","Dị ứng hải sản","Trào ngược dạ dày",
            "U dưới niêm","Rối loạn tiêu hóa","Hen suyễn","Co thắt đại tràng"};
        model = (DefaultComboBoxModel) cboChuanDoan.getModel();
        model.removeAllElements();
        for (int i = 0; i < chuandoan.length; i++) {
            model.addElement(chuandoan[i]);
        }
    }
    public void initTable() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachHDTT.getModel();
        model.setColumnIdentifiers(new String[]{"MaHDT","Chuẩn Đoán","Ngày Xuất","MaBN","MaNV"});
    }
    
     public void initTablee() {
        DefaultTableModel model = (DefaultTableModel) tblHDCT.getModel();
        model.setColumnIdentifiers(new String[]{"MaHDCT","MaDT","Tên Thuốc","Số Lượng","Đơn Gía","Tiền"});
    }
     
      public void initTableee() {
        DefaultTableModel model = (DefaultTableModel) tblKeThuoc.getModel();
        model.setColumnIdentifiers(new String[]{"Tên Thuốc","Số Lượng","Liều Dùng"});
    }

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachHDTT.getModel();
        model.setRowCount(0);

        try {
            String keyword = txtTimKiem.getText();
            List<HoaDonThuocPK> list = dao.selectByKeyword(keyword);
            for (HoaDonThuocPK hdt : list) {
                Object[] row = {
                    hdt.getMaDT(),
                    hdt.getChuanDoan(),
                    hdt.getNgayXuat(),
                    hdt.getMaBN(),
                    hdt.getMaNV(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
        
     void fillTableHDCT(){
        DefaultTableModel model = (DefaultTableModel) tblHDCT.getModel();
        model.setRowCount(0);  
        String MaDT = txtMaHDT.getText();
        List<Object[]> list = dao.getHDCT(MaDT);
        for(Object[] row : list){           
            model.addRow(row);
        }
    }
//     void TongHoaDon(){
//         String madt = txtMaHDT.getText();
//          List<HoaDonThuocPK> kq = dao.getTT(madt);
//     txtTongHoaDn.setText((String) kq);
//        
//    }
    void setForm(HoaDonThuocPK hdt) {
        txtMaHDT.setText(hdt.getMaDT());
        cboChuanDoan.setSelectedItem(hdt.getChuanDoan());      
        JDCNgayXuat.setDate(hdt.getNgayXuat()); 
        txtMaBN.setText(hdt.getMaBN());
        txtMaNV.setText(hdt.getMaNV());
//        txtTongHoaDn.setText(TOOL_TIP_TEXT_KEY);
    }

    void clearForm() {
        HoaDonThuocPK hdt = new HoaDonThuocPK();
        this.setForm(hdt);
        this.row = -1;
    }

    HoaDonThuocPK getForm() {
        HoaDonThuocPK hdt = new HoaDonThuocPK();
        hdt.setMaDT(txtMaHDT.getText());
        hdt.setChuanDoan(cboChuanDoan.getSelectedItem().toString());  
        hdt.setNgayXuat(JDCNgayXuat.getDate());
        hdt.setMaBN(txtMaBN.getText());
        hdt.setMaNV(txtMaNV.getText());
        return hdt;
    }

    void insert() {
        HoaDonThuocPK nv = this.getForm();
        try {
            dao.insert(nv);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "thêm mới thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "thêm mới thành công");
        }
    }

    void edit() {
        String mahdt = (String) tblDanhSachHDTT.getValueAt(this.row, 0);
        HoaDonThuocPK hdt = dao.selectById(mahdt);
        this.setForm(hdt);
//        NhanVien.setSelectedIndex(0);

    }
    
    
   

    void delete() {
        String mahdt = txtMaHDT.getText();
        try {
            dao.delete(mahdt);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Xóa thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            MsgBox.alert(this, "Xóa thất bại!");
        }
    }

    void update() {
        HoaDonThuocPK model = getForm();
        try {
            dao.update(model);
            this.fillTable();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }
    private void timKiem() {
        this.fillTable();
        this.clearForm();
        this.row = -1;
//        this.updateStatus();
    }
   public void getsum(){
            float total = 0;

            for (int i = 0; i < tblHDCT.getRowCount(); i++) {
                int amount = (int) Float.parseFloat(tblHDCT.getValueAt(i, 4).toString());
                //int amount = Integer.parseInt(tblHDCT.getValueAt(i, 5).toString());
                total = total + amount;
            }

            txtTongHoaDn.setText("" + Integer.toString((int) total));
    
}
    
}
